$(document).ready(function(){
    $("#d-1").mouseenter(function(){
        $("#d-1").css("background-color","#63B8FF");
    });
    $("#d-1").mouseleave(function(){
        $("#d-1").css("background-color","");
    });
    $("#d-2").mouseenter(function(){
        $("#d-2").css("background-color","#63B8FF");
    });
    $("#d-2").mouseleave(function(){
        $("#d-2").css("background-color","");
    });
    $("#d-3").mouseenter(function(){
        $("#d-3").css("background-color","#63B8FF");
    });
    $("#d-3").mouseleave(function(){
        $("#d-3").css("background-color","");
    });
    $("#d-4").mouseenter(function(){
        $("#d-4").css("background-color","#63B8FF");
    });
    $("#d-4").mouseleave(function(){
        $("#d-4").css("background-color","");
    });
    $("#d-5").mouseenter(function(){
        $("#d-5").css("background-color","#63B8FF");
    });
    $("#d-5").mouseleave(function(){
        $("#d-5").css("background-color","");
    });
    $("#d-6").mouseenter(function(){
        $("#d-6").css("background-color","#63B8FF");
    });
    $("#d-6").mouseleave(function(){
        $("#d-6").css("background-color","");
    });
    $("#d-7").mouseenter(function(){
        $("#d-7").css("background-color","#63B8FF");
    });
    $("#d-7").mouseleave(function(){
        $("#d-7").css("background-color","");
    });
    $("#d-8").mouseenter(function(){
        $("#d-8").css("background-color","#63B8FF");
    });
    $("#d-8").mouseleave(function(){
        $("#d-8").css("background-color","");
    });
    $("#d-9").mouseenter(function(){
        $("#d-9").css("background-color","#63B8FF");
    });
    $("#d-9").mouseleave(function(){
        $("#d-9").css("background-color","");
    });
    $("#d-10").mouseenter(function(){
        $("#d-10").css("background-color","#63B8FF");
    });
    $("#d-10").mouseleave(function(){
        $("#d-10").css("background-color","");
    });
    $("#d-11").mouseenter(function(){
        $("#d-11").css("background-color","#63B8FF");
    });
    $("#d-11").mouseleave(function(){
        $("#d-11").css("background-color","");
    });
});